### ISSUE TITLE
Can micropython.bin be minified?

### ISSUE THREAD

**Issue by Lemenxzy** [glenn20/micropython-esp32-ota#4]
Thank you very much for this library，It opened my eyes to more possibilities.

But micropython.bin is too large,

Could you please tell me if there is a good OTA method to reduce the size of micropython.bin, or to only update the code changes without updating the original micropython.bin?How should the partition be established? I have the idea of not updating micropython.bin, but updating the "vfs" partition, but I lack experience with micropython and would like to ask if there is any method to do this?

**Comment by glenn20** [comment]
micropython.bin is the micropython binary firmware itself and is this size because of all the compiled in featues. The only method I can think of to reduce the size of micropython.bin is to recompile micropython and remove many of the compiled in features (it will still be fairly "big").

There are various options to update the python files on the filesystem, including eg. https://github.com/rdehuyss/micropython-ota-updater.
